# .streamlit/secrets.toml

[connections.snowflake]
account = "BKEXPPL.ZA02157"
user = "Maarten"
password = "Sn0wflake123!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
